version: "3.2"
services:
  web:
    build:
      context: .
    image: "php-ext"
    ports:
      - "8080:80"
    volumes:
      - type: "bind"
        source: ""
        target: "/var/www/html"
    networks:
      - "backend"
  db:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=development"
      - "MYSQL_ROOT_PASSWORD=password"
    volumes:
      - type: "bind"
        source: ""
        target: "/var/lib/mysql"
    networks:
      backend:
        aliases:
          - mysql
networks:
  backend:
